const menuButton=document.querySelector('.menu-button');const navLinks=document.querySelector('.nav-links');const setMenu=open=>{navLinks.classList.toggle('is-open',open);menuButton.setAttribute('aria-expanded',String(open));menuButton.textContent=open?'Close':'Menu'};menuButton.addEventListener('click',()=>setMenu(!navLinks.classList.contains('is-open')));navLinks.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>setMenu(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});

const chips=[...document.querySelectorAll('.question-chip')];const answers=[...document.querySelectorAll('.answer')];let active=0;let heroTimer;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function showAnswer(index,userInitiated=false){if(index===active&&userInitiated)return;const previous=answers[active];const next=answers[index];chips.forEach((chip,i)=>chip.classList.toggle('is-active',i===index));if(window.gsap&&!reduced){gsap.killTweensOf([previous,next]);gsap.to(previous,{y:-24,opacity:0,duration:.35,ease:'power2.in',onComplete:()=>{previous.classList.remove('is-active');next.classList.add('is-active');gsap.fromTo(next,{y:34,opacity:0},{y:0,opacity:1,duration:.7,ease:'power3.out'})}})}else{previous.classList.remove('is-active');next.classList.add('is-active')}active=index;resetHeroTimer()}
function resetHeroTimer(){clearInterval(heroTimer);heroTimer=setInterval(()=>showAnswer((active+1)%answers.length),4200)}chips.forEach((chip,index)=>chip.addEventListener('click',()=>showAnswer(index,true)));answers[0].style.opacity='1';resetHeroTimer();

document.querySelectorAll('.case-media').forEach(media=>{const toggle=()=>media.classList.toggle('is-open');media.addEventListener('click',toggle);media.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})});
document.querySelectorAll('.replace-link').forEach(link=>link.addEventListener('click',e=>e.preventDefault()));

const cursor=document.querySelector('.cursor');const hasFinePointer=window.matchMedia('(pointer: fine)').matches;if(cursor&&hasFinePointer&&!reduced){document.body.classList.add('has-custom-cursor');let mouseX=window.innerWidth/2,mouseY=window.innerHeight/2,cursorX=mouseX,cursorY=mouseY;window.addEventListener('mousemove',event=>{mouseX=event.clientX;mouseY=event.clientY},{passive:true});const moveCursor=()=>{cursorX+=(mouseX-cursorX)*.18;cursorY+=(mouseY-cursorY)*.18;cursor.style.transform=`translate3d(${cursorX}px,${cursorY}px,0)`;requestAnimationFrame(moveCursor)};moveCursor();document.querySelectorAll('a,button,.case-media').forEach(element=>{element.addEventListener('mouseenter',()=>cursor.classList.add('is-hovering'));element.addEventListener('mouseleave',()=>cursor.classList.remove('is-hovering'))})}

if(window.gsap&&!reduced){gsap.registerPlugin(ScrollTrigger);gsap.set('.answer.is-active',{opacity:1});const intro=gsap.timeline({defaults:{ease:'power3.out'}});intro.from('.nav',{y:-70,opacity:0,duration:.7}).from('.hero-topline',{y:20,opacity:0,duration:.5},'-=.3').from('.question-chip',{x:-30,opacity:0,stagger:.09,duration:.55},'-=.2').from('.answer.is-active>*',{y:55,opacity:0,stagger:.11,duration:.75},'-=.4').from('.hero-bottom',{y:30,opacity:0,duration:.6},'-=.35');gsap.utils.toArray('.reveal').forEach(el=>gsap.to(el,{y:0,opacity:1,duration:.9,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 86%',once:true}}));gsap.utils.toArray('.case-card').forEach(card=>{const media=card.querySelector('.case-media');gsap.from(media,{scale:.94,y:50,duration:1,ease:'power3.out',scrollTrigger:{trigger:card,start:'top 80%',once:true}})});gsap.to('.about-stamp',{rotate:5,scrollTrigger:{trigger:'.about',start:'top bottom',end:'bottom top',scrub:1}})}else{document.querySelectorAll('.reveal').forEach(el=>{el.style.opacity='1';el.style.transform='none'})}